name: S3 Transfer
on:
  push:
    tags: 
      - 'ag*'
    
 
env:
  AWS_REGION: us-east-2
  DEPLOYMENT_NAME: Agreement-web

  STATIC_FILES_DIR: build/
  DOMAIN_PREFIX: agreement-web-ui
  # # CFI: 
  
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev      
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install -g serverless  
      - run: npm install -g serverless-s3-sync
      

      
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAXJL77BAHDSC6WQX3
          aws-secret-access-key: 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
          aws-region: us-east-2
          role-to-assume: agreement-assets-role
          role-external-id: agreement
          role-duration-seconds: 1200
          role-session-name: agreementwebdeploysession

      - name:  deploy
        run: sls deploy --stage dev

      # - name: Invalidation
      #   shell: bash
      #   run: |
      #     aws cloudfront create-invalidation --distribution-id ${{ env.CFI }} --paths "/*" 
